stages:
  - sast

services:
  - docker:dind

SAST:
  stage: sast
#  image: registry.ddos-guard.net/semgrep-sast:latest-nonroot
  image: semgrep/semgrep:latest-nonroot
  tags: [docker]
  variables:
    GIT_STRATEGY: clone
  script:
    - semgrep ci --junit-xml > ./rules/result.xml --config=./rules/
    - cat ./rules/result.xml
  artifacts:
    paths:
      - ./rules/result.xml
    reports:
      junit: ./rules/result.xml
    when: always
    expire_in: 1 week
  allow_failure: true