SAST:
  stage: sast
#  image: "$CI_REGISTRY/semgrep-sast:latest-nonroot"
  image: semgrep/semgrep:latest-nonroot
  tags: [docker]
  services:
    - python:3.8-slim
  script:
  #  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@git.ddos-guard.net/web/sast
  # клонирование sast с тестового репозитория
    - git clone http://gitlab.test-vm1.testdomain.org/user-git-1/sast-2
  #  - semgrep --metrics=off --config=./sast/rules/ ./
  # настройки для работы на тестовой машине:
  #  - semgrep --metrics=off --config=./sast-2/rules/ ./
    - semgrep ci --json > ./sast-2/result.json --config=./sast-2/rules/ --no-suppress-errors -v
    - python json-to-junit-parser.py
    - ls -la
  artifacts:
    paths:
      - ./sast-2/result.json
      - ./sast-2/result.xml
    reports:
      junit: ./sast-2/result.xml
    when: always
#  allow_failure: true
