SAST:
  stage: sast
  image: "$CI_REGISTRY/semgrep-sast:latest-nonroot"
  tags: [docker]
  script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@git.ddos-guard.net/web/sast
    - semgrep --metrics=off --config=./sast/rules/ ./
