SAST:
  stage: sast
#  image: "$CI_REGISTRY/semgrep-sast:latest-nonroot"
  image: semgrep/semgrep:latest-nonroot
  tags: [docker]
  script:
  #  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@git.ddos-guard.net/web/sast
  # клонирование sast с тестового репозитория
    - git clone http://gitlab.test-vm1.testdomain.org/user-git-1/sast-2
  #  - semgrep --metrics=off --config=./sast/rules/ ./
  # настройки для работы на тестовой машине:
  #  - semgrep --metrics=off --config=./sast-2/rules/ ./
    - semgrep ci --junit-xml > ./sast-2/rules/result.xml --config=./sast-2/rules/
  artifacts:
    paths:
      - ./sast-2/rules/result.xml
    reports:
      sast: ./sast-2/rules/result.xml
    when: always
  only:
   - merge_requests
   - branches
#  allow_failure: true